/**
 * Canonical error codes from the design's Error Handling table.
 * Kept as a single source of truth so services and the gateway agree on codes.
 */
export const ERROR_CODES = {
  // Registration / Authentication
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  PASSWORD_LENGTH_INVALID: 'PASSWORD_LENGTH_INVALID',
  VERIFICATION_LINK_INVALID: 'VERIFICATION_LINK_INVALID',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  // Profile
  PURPOSE_STATEMENT_TOO_LONG: 'PURPOSE_STATEMENT_TOO_LONG',
  PROFILE_UPDATE_FAILED: 'PROFILE_UPDATE_FAILED',
  // Media
  UNSUPPORTED_IMAGE_FORMAT: 'UNSUPPORTED_IMAGE_FORMAT',
  IMAGE_TOO_LARGE: 'IMAGE_TOO_LARGE',
  MEDIA_STORAGE_FAILED: 'MEDIA_STORAGE_FAILED',
  ALT_TEXT_INVALID: 'ALT_TEXT_INVALID',
  // Interest
  INTEREST_SAVE_FAILED: 'INTEREST_SAVE_FAILED',
  INTEREST_SELECTION_INVALID: 'INTEREST_SELECTION_INVALID',
  INTEREST_LABEL_INVALID: 'INTEREST_LABEL_INVALID',
  // Comment
  COMMENT_TOO_LONG: 'COMMENT_TOO_LONG',
  COMMENT_EMPTY: 'COMMENT_EMPTY',
  NESTING_DEPTH_EXCEEDED: 'NESTING_DEPTH_EXCEEDED',
  COMMENT_SAVE_FAILED: 'COMMENT_SAVE_FAILED',
  // Event
  INVALID_EVENT_DATES: 'INVALID_EVENT_DATES',
  EDIT_WINDOW_CLOSED: 'EDIT_WINDOW_CLOSED',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  REGISTRATION_CLOSED: 'REGISTRATION_CLOSED',
  // Search
  SEARCH_QUERY_TOO_LONG: 'SEARCH_QUERY_TOO_LONG',
  SEARCH_TIMEOUT: 'SEARCH_TIMEOUT',
  SEARCH_UNAVAILABLE: 'SEARCH_UNAVAILABLE',
  // Generic
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
